server:
  global:
    scrape_interval: 15s # Specifies the time interval at which Prometheus will scrape a
  alerting:
    alertmanagers:
      - scheme: http
        static_configs:
        - targets:
          - alertmanager:9093
  scrape_configs:
    - job_name: 'prometheus'
      metrics_path: /actuator/prometheus
      static_configs:
        - targets: ['localhost:8080'] # Prometheus should scrape metrics from the instance